"""add prescribed weight and reps to gym workout details

Revision ID: 8bcc257c3529
Revises: d1e2f3a4b5c6
Create Date: 2026-09-08 12:12:32.857839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcc257c3529'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_workout_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescribed_weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prescribed_reps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_workout_details', schema=None) as batch_op:
        batch_op.drop_column('prescribed_reps')
        batch_op.drop_column('prescribed_weight_kg')

    # ### end Alembic commands ###
